language: ruby
matrix:
  include:
    # See https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
    # OS X 10.11
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    # OS X 10.10
    - os: osx
      osx_image: xcode7.1
    # OS X 10.9
    - os: osx
      osx_image: beta-xcode6.2
install:
  - brew update
script:
  - brew audit --strict ./*.rb
  - brew install --verbose --build-bottle ./*.rb
